coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 90%
        threshold: 0%

  precision: 2
  round: down

ignore:
  - "adapters/mocks/**"
  - ".*_test\\.go$"        # ignore every Go test file

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      method: true
      macro: true
