repos:
  - repo: local
    hooks:
      - id: goimports
        name: Run goimports
        entry: goimports -w .
        language: system
        types: [go]
      - id: golangci-lint
        name: Run golangci-lint
        entry: golangci-lint run ./...
        language: system
        types: [go]
        pass_filenames: false