services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: chatheon
      POSTGRES_PASSWORD: chatheon_passwd
      POSTGRES_DB: chatheon_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d


  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=chatheon
      - DB_PASSWORD=chatheon_passwd
      - DB_NAME=chatheon_db
    depends_on:
      - db

volumes:
  postgres_data: